import { findField, formatBytes, type MetadataField, type PhotoReport } from './photo-inspector';

function pick(report: PhotoReport, patterns: RegExp[]) {
  return findField(report.fields, patterns);
}

function cleanLabel(label: string) {
  return label
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replaceAll('_', ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function section(title: string, fields: MetadataField[]) {
  if (!fields.length) return '';
  const lines = fields.map((field) => `${cleanLabel(field.name)}: ${field.display}`);
  return `${title.toUpperCase()}\n${'─'.repeat(Math.min(32, title.length + 4))}\n${lines.join('\n')}`;
}

export function buildShareText(
  report: PhotoReport,
  options: { includeLocation?: boolean; complete?: boolean } = {},
) {
  const includeLocation = options.includeLocation ?? true;
  const device = [pick(report, [/exif\.Make$/i]), pick(report, [/exif\.Model$/i])].filter(Boolean).join(' ');
  const dimensions = report.image ? `${report.image.width} × ${report.image.height} px (${report.image.megapixels} MP)` : pick(report, [/Image Width$/i]);
  const summary = [
    `PHOTO DATA FINDER REPORT`,
    `Generated by Photo Data Finder by Asher Menachem`,
    ``,
    `FILE`,
    `────`,
    `Name: ${report.file.name}`,
    `Size: ${formatBytes(report.file.size)} (${report.file.size.toLocaleString('en-US')} bytes)`,
    `Format: ${report.file.detectedType}`,
    `MIME type: ${report.file.type}`,
    ...(dimensions ? [`Dimensions: ${dimensions}`] : []),
    `Metadata fields: ${report.fields.length}`,
    ``,
    `CAPTURE SUMMARY`,
    `───────────────`,
    `Device: ${device || 'Not embedded'}`,
    `Lens: ${pick(report, [/LensModel$/i, /LensID$/i, /LensType$/i]) || 'Not embedded'}`,
    `Captured: ${pick(report, [/DateTimeOriginal$/i, /CreateDate$/i, /DateCreated$/i]) || 'Not embedded'}`,
    `Exposure: ${pick(report, [/ExposureTime$/i, /ShutterSpeedValue$/i]) || 'Not embedded'}`,
    `Aperture: ${pick(report, [/FNumber$/i, /ApertureValue$/i]) || 'Not embedded'}`,
    `ISO: ${pick(report, [/ISOSpeedRatings$/i, /PhotographicSensitivity$/i]) || 'Not embedded'}`,
    ...(includeLocation ? [
      `Location: ${report.gps ? `${report.gps.latitude.toFixed(7)}, ${report.gps.longitude.toFixed(7)}` : 'Not embedded'}`,
      ...(report.gps?.altitude ? [`Altitude: ${report.gps.altitude}`] : []),
    ] : [`Location: Hidden from this shared copy`]),
    ``,
    `INTEGRITY`,
    `─────────`,
    `SHA-256: ${report.file.sha256}`,
  ];

  if (!options.complete) return summary.join('\n');

  const grouped = Array.from(new Set(report.fields.map((field) => field.group)))
    .filter((group) => includeLocation || group !== 'Location')
    .map((group) => section(group, report.fields.filter((field) => field.group === group)))
    .filter(Boolean);

  return [
    ...summary,
    ``,
    `COMPLETE DECODED METADATA`,
    `═════════════════════════`,
    grouped.join('\n\n'),
    ``,
    `Decoded locally. Metadata removed before inspection cannot be recovered.`,
  ].join('\n');
}
